name: Build Node.js Bindings

on:
  push:
    branches:
      - main
      - build
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        
    steps:
      - name: Set architecture
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo "arch=linux-x64" >> $GITHUB_ENV
          else
            echo "arch=darwin-x64" >> $GITHUB_ENV
          fi
  
      - name: Install build dependencies (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install llvm cmake protobuf

      - name: Install build dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libprotobuf-dev protobuf-compiler

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and build
        run:  npm install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cld3-${{ env.arch }}.node
          path: build/Release/cld3.node
