name: Test CLD3 bindings

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    steps:
      - name: Install build dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libprotobuf-dev protobuf-compiler

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and build
        run: npm install && npm run build

      - name: Run tests
        run: npm run test
